# Generated by Django 4.2.5 on 2023-11-29 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_rename_username_user_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="Username",
        ),
    ]
